ogrlist update to work on MacOS Bash, small bugfix

diff --git a/linux_bash/exec/ogrlist b/linux_bash/exec/ogrlist
--- a/linux_bash/exec/ogrlist
+++ b/linux_bash/exec/ogrlist
@@ -4,9 +4,16 @@
 set -uo pipefail
 
 ## Script globals
-script_file=$(readlink -f "${BASH_SOURCE[0]}"); export CURRENT_PARENT_BASH_SCRIPT_FILE="$script_file"
-script_dir=$(dirname "$script_file")
-script_name=$(basename "$script_file")
+script_name=$(basename "${BASH_SOURCE[0]}")
+script_dir=$({ cd "$(dirname "${BASH_SOURCE[0]}")" || { echo "Failed to access script file directory" >&2; exit; } } && pwd)
+script_dir_abs=$({ cd "$(dirname "${BASH_SOURCE[0]}")" || { echo "Failed to access script file directory" >&2; exit; } } && pwd -P)
+script_file="${script_dir}/${script_name}"
+if [ -L "${BASH_SOURCE[0]}" ]; then
+    script_file_abs=$(readlink "${BASH_SOURCE[0]}")
+else
+    script_file_abs="${script_dir_abs}/${script_name}"
+fi
+export CURRENT_PARENT_BASH_SCRIPT_FILE="$script_file"
 script_args=("$@")
 
 ## Script imports
@@ -138,7 +145,7 @@ while (( "$#" )); do
             exit_script_with_status 1
         fi
 
-        if [ "$arg_opt_nargs_do_shift" = true ]; then
+        if [ "$arg_opt_nargs_do_shift" = true ] && (( arg_opt_nargs >= 1 )); then
             for arg_num in $(seq 1 $arg_opt_nargs); do
                 shift
                 arg_val="$1"
@@ -184,10 +191,10 @@ fi
 if [ -z "$layer_name" ]; then
     cmd="ogrinfo -so -al '${dbase_path}' | grep '^Layer name:'"
 elif [ -z "$field_name" ]; then
-    cmd="ogrinfo -so -al '${dbase_path}' | sed -n '/^Layer name: ${layer_name}/,\${p;/^[[:space:]]*\$/q}' | grep -E '^[^[:space:]]+\: [^[:space:]]+ \([0-9]+\.?[0-9]*\)$'"
+    cmd="ogrinfo -so -al '${dbase_path}' | sed -n '/^Layer name: ${layer_name}/,\${p;/^[[:space:]]*\$/q;}' | grep -E '^[^[:space:]]+\: [^[:space:]]+ \([0-9]+\.?[0-9]*\)$'"
 else
     awk_cmd='BEGIN { csv="" } { val=$0; if (val=="") { if (csv!="") print csv; csv=""; } else if (csv=="") { csv=val; } else { csv=sprintf("%s'"${delimiter}"'%s", csv, val); } } END { if (csv!="") print csv; }'
-    cmd="ogrinfo -dialect sqlite -sql 'SELECT ${field_name} FROM ${layer_name}' '${dbase_path}' | sed -e '1,/OGRFeature(SELECT):0/d' | grep -E '(^$| = )' | cut -d'=' -f2- | cut -d' ' -f2- | awk '${awk_cmd}'"
+    cmd="ogrinfo -dialect sqlite -sql 'SELECT ${field_name} FROM \"${layer_name}\"' \"${dbase_path}\" | sed -e '1,/OGRFeature(SELECT):0/d' | grep -E '(^$| = )' | cut -d'=' -f2- | cut -d' ' -f2- | awk '${awk_cmd}'"
     if [ "$print_header" = true ]; then
         cmd="echo '${field_name//,/${delimiter}}' ; ${cmd}"
     fi
